DBT_PRONO:
  outputs:
    prod:
      account: #ACCOUNT#
      database: #DATABASE#
      user: #USER#
      password: #PASSWORD#
      role: ACCOUNTADMIN
      schema: LANDING
      threads: 1
      type: snowflake
      warehouse: COMPUTE_WH
  target: prod
